### ISSUE TITLE
Elpis fails with white screen when uploading wav file to dataset

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis#298]
Reproduce this by creating a new dataset, then upload a WAV file (without its accompanying ELAN file). Elpis expects an eaf to get tier selection from, and fails with this message in the browser console.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'selection_mechanism')
    at GeneratedUI.js:31:49
    at Iu (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at $o (react-dom.production.min.js:122:325)
    at _u (react-dom.production.min.js:261:308)
    at react-dom.production.min.js:261:215
    at M (scheduler.production.min.js:16:224)
    at j.port1.onmessage (scheduler.production.min.js:12:346)
```

Should be easily fixed by only doing the selection stuff when an elan file is uploaded.

**Comment by benfoley** [comment]
fixed with #305
