### ISSUE TITLE
Elpis breaks if additional corpus/wordlist files are added before eaf files

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis#96]
To replicate, start a new session. Add a text file (eg corpus.txt). Terminal reports 
```
172.17.0.1 - - [22/Jul/2020 07:55:36] "POST /api/dataset/files HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/lib/python3.6/site-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/elpis/elpis/endpoints/dataset.py", line 58, in wrapper
    return f(dataset, *args, **kwargs)
  File "/elpis/elpis/endpoints/dataset.py", line 74, in files
    dataset.validate()
  File "/elpis/elpis/engines/common/objects/dataset.py", line 329, in validate
    self.importer.validate_files(extention, paths)
AttributeError: 'NoneType' object has no attribute 'validate_files'
```

**Comment by benfoley** [comment]
closed with #96
